---
details:
    title: gl bro
    description: The Best Is Yet To Come
    loading: 🥚🥚🥚 sent you a message
    body: im sorry i have 2 leave the lobby but i will never forget you. you will always be my teammate my partner and most of all my brother good luck in future games and remember god loves you and has a plan 4 u. peace bro
